### PR TITLE
Update config.json

### PR DESCRIPTION
**Pull request by Success1-coder**

### CODE REVIEW

**Comment by marian2js** [comment]
Thank you for taking the time to contribute. Your change would allow anyone (even without an account) to create posts. This would create a huge amount of spam. The website has already been targeted by many automated spam bots.

What needs to be done in that regard is:
1.- Only accept posts from verified accounts. We already have email verification process but it's not checked before creating a post.
2.- Blacklist email providers like mailinator or whitelist known providers.
3.- Optionally we could require a minimum amount of points before creating a post. Points could be obtained with upvoted comments. I've seen many spam bots using Google/Facebook login or completing the email verification process. I'm not sure if spam is created manually by real people or if they use hacked accounts.

**Comment by Success1-coder** [comment]
Okay, Thanks Sir.
Since I cannot make changes, I would really like to see how the platform
works,
I came across your platform on GitHub here and I was really impressed, i
wiil like to have the same platform just like your own. Sir, I will really
be grateful if you teach me  how to deploy it, am still a learner. Thanks,
will be waiting for your reply.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by marian2js** [comment]
For deploying the project you can use the docker-compose file. Run `docker-compose up` on the root of the project and it will initialise everything.

The backend uses Commun, you can check the project docs here: https://github.com/commundev/commun

**Comment by Success1-coder** [comment]
Using Ubuntu server is okay right?

**Comment by marian2js** [comment]
@Success1-coder yes, it's fine.

**Comment by Success1-coder** [comment]
Sorry Sir, please can you give me a summary like a list of how i will go be
able to deploy successfully?

**Comment by marian2js** [comment]
Install docker and docker-compose. Then run `docker-compose up -d --build` and this will set everything up on your server, including frontend, backend, mongodb, redis and nginx.
You can find more on docker's documentation: https://docs.docker.com/compose/

**Comment by Success1-coder** [comment]
Not working Sir, giving me this error message "Can't find a suitable configuration file in this directory or any parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml"

**Comment by marian2js** [comment]
Are you sure you are running the command in the root directory of this project, where docker-compose.yml is?
Please check running an ls that the file is in your system.

**Comment by Success1-coder** [comment]
how do i upload the file to my ubuntu server?

**Comment by marian2js** [comment]
@Success1-coder I am sorry, these questions are not related to the project but to basic computer systems. Please use Google to find out how to clone the repository and other basic tasks you will need to do in order to deploy and run a server.
This project is basically an express server with a nginx reverse proxy. Please read the documentation of these technologies and refer your doubts to StackOverflow or the specific community for each technology.

**Comment by Success1-coder** [comment]
Okay, thanks, I'm grateful

**Comment by Success1-coder** [comment]
Sorry Sir the last question i promise, 
I have the file on my root directory now but it's saying 

WARNING: The NGINX_CONFIG_FILE variable is not set. Defaulting to a blank string.
WARNING: The REDIS_EXPOSE_PORT variable is not set. Defaulting to a blank string.
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.fs-redis.ports is invalid: Invalid port ":", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]

**Comment by marian2js** [comment]
Hi, this questions are totally fine. I'm sorry there isn't enough documents around this.

You need to add .env file on the same folder as the docker-compose file.
The file should contain there variables:

```
NGINX_CONFIG_FILE=finsharing.com.conf # name of the file in ./config/nginx
REDIS_EXPOSE_PORT=9999 # any port will be fine
```

If you plan to deploy this with your own domain, you will have to replace the domain in the files under ./config/nginx

**Comment by Success1-coder** [comment]
Just Like this "NGINX_CONFIG_FILE=my domain name.conf # name of the file in ./config/nginx
REDIS_EXPOSE_PORT=9999 # any port will be fine", right?

**Comment by Success1-coder** [comment]
Sir, I have successfully installed it now, but I can't access my backend dashboard, please how do I do that?

**Comment by Success1-coder** [comment]
Showing "502 Bad Gateway"nginx/1.19.2"

**Comment by Success1-coder** [comment]
Please sir answer me

**Comment by marian2js** [comment]
I don't know with just that error, probably something miss configured on your nginx. Please refer these questions to the appropriate communities. As I mention before this channel is for issues with the project and it's not intended for this kind of questions, specially about deployment and server configurations that have little to do with this project and more with deploying an express server. Please refer your questions to StackOverflow where you are going to get the appropriate responses.

**Comment by Success1-coder** [comment]
Sir can you tell me the recommended servers to use to deploy this project?

**Comment by marian2js** [comment]
Since the app is just an express server, any platform supported by express would be fine, an Ubuntu server like you mentioned before is totally fine.

**Pull request closed without merging**
